import type { TtsPreset } from './types'
import { MIMO_OPENAI_BASE_URL, MIMO_TOKEN_PLAN_SGP_BASE_URL } from './providers'

export const QWEN_DASHSCOPE_CN_TTS_BASE_URL = 'https://dashscope.aliyuncs.com/api/v1'
export const QWEN_DASHSCOPE_INTL_TTS_BASE_URL = 'https://dashscope-intl.aliyuncs.com/api/v1'
export const QWEN_TTS_DEFAULT_MODEL = 'qwen3-tts-flash'
export const QWEN_TTS_DEFAULT_VOICE = 'Jennifer'

export const mimoTtsModels = [
  { value: 'mimo-v2.5-tts', label: 'MiMo-V2.5-TTS' },
  { value: 'mimo-v2.5-tts-voicedesign', label: 'MiMo-V2.5-TTS-VoiceDesign' },
  { value: 'mimo-v2.5-tts-voiceclone', label: 'MiMo-V2.5-TTS-VoiceClone' },
  { value: 'mimo-v2-tts', label: 'MiMo-V2-TTS' },
]

export const mimoTtsVoices = [
  'Mia',
  'Chloe',
  'Milo',
  'Dean',
  'mimo_default',
  '冰糖',
  '茉莉',
  '苏打',
  '白桦',
  'default_en',
  'default_zh',
]

export const qwenTtsModels = [
  { value: 'qwen3-tts-flash', label: 'Qwen3-TTS-Flash' },
  { value: 'qwen3-tts-instruct-flash', label: 'Qwen3-TTS-Instruct-Flash' },
  { value: 'qwen3-tts-vd-2026-01-26', label: 'Qwen3-TTS-VD Custom Voice' },
  { value: 'qwen-tts-latest', label: 'Qwen-TTS Latest' },
  { value: 'qwen-tts', label: 'Qwen-TTS' },
]

export const qwenTtsVoices = [
  'Jennifer',
  'Aiden',
  'Cherry',
  'Serena',
  'Ethan',
  'Chelsie',
  'Momo',
  'Vivian',
  'Moon',
  'Maia',
  'Kai',
  'Nofish',
  'Bella',
  'Ryan',
  'Katerina',
  'Eldric Sage',
  'Mia',
  'Mochi',
  'Bellona',
  'Vincent',
  'Bunny',
  'Neil',
  'Elias',
  'Arthur',
  'Nini',
  'Seren',
  'Pip',
  'Stella',
  'Bodega',
  'Sonrisa',
  'Alek',
  'Dolce',
  'Sohee',
  'Ono Anna',
  'Lenn',
  'Emilien',
  'Andre',
  'Radio Gol',
  'Jada',
  'Dylan',
  'Li',
  'Marcus',
  'Roy',
  'Peter',
  'Sunny',
  'Eric',
  'Rocky',
  'Kiki',
]

export const ttsPresets: TtsPreset[] = [
  {
    id: 'disabled',
    label: '关闭 TTS',
    provider: 'disabled',
    base_url: '',
    model: '',
    voice: '',
    note: '只使用视频原声音频，不额外生成 AI 朗读。',
    key_hint: '不需要填写',
  },
  {
    id: 'mimo-token-plan-sgp-tts',
    label: 'MIMO SGP TTS',
    provider: 'mimo',
    base_url: MIMO_TOKEN_PLAN_SGP_BASE_URL,
    model: 'mimo-v2.5-tts',
    voice: 'Mia',
    note: '新加坡 Token Plan 专属 TTS；走 /chat/completions + audio，不是 /audio/speech。',
    key_hint: 'Token Plan 专属 API Key，通常是 tp-...',
  },
  {
    id: 'mimo-v25-tts',
    label: 'MIMO V2.5 TTS',
    provider: 'mimo',
    base_url: MIMO_OPENAI_BASE_URL,
    model: 'mimo-v2.5-tts',
    voice: 'Mia',
    note: '小米 MiMo V2.5 基础语音合成；支持 Mia、Chloe、Milo、Dean 等内置声音。',
    key_hint: '公共平台 Key，通常是 sk-...；tp- Key 请选 SGP TTS。',
  },
  {
    id: 'mimo-v25-voice-design',
    label: 'MIMO VoiceDesign',
    provider: 'mimo',
    base_url: MIMO_OPENAI_BASE_URL,
    model: 'mimo-v2.5-tts-voicedesign',
    voice: 'A warm, clear English teacher voice with natural pacing.',
    note: 'MiMo V2.5 声音设计模型；Voice 栏填写声音描述，不填内置 voice_id。',
    key_hint: 'MiMo API Key',
  },
  {
    id: 'mimo-v25-voice-clone',
    label: 'MIMO VoiceClone',
    provider: 'mimo',
    base_url: MIMO_OPENAI_BASE_URL,
    model: 'mimo-v2.5-tts-voiceclone',
    voice: 'mimo_default',
    note: 'MiMo V2.5 声音克隆模型；当前先保留模型入口，参考平台要求填 voice。',
    key_hint: 'MiMo API Key',
  },
  {
    id: 'mimo-v2-tts',
    label: 'MIMO V2 TTS',
    provider: 'mimo',
    base_url: MIMO_OPENAI_BASE_URL,
    model: 'mimo-v2-tts',
    voice: 'default_en',
    note: 'MiMo V2 语音合成模型，适合旧套餐；常用 default_en、default_zh、mimo_default。',
    key_hint: 'MiMo API Key',
  },
  {
    id: 'qwen3-tts-flash-cn',
    label: 'Qwen3 TTS 美语女声',
    provider: 'qwen',
    base_url: QWEN_DASHSCOPE_CN_TTS_BASE_URL,
    model: QWEN_TTS_DEFAULT_MODEL,
    voice: QWEN_TTS_DEFAULT_VOICE,
    note: '阿里云百炼北京地域 Qwen3-TTS；Jennifer 是官方美语女声，更适合英语学习卡片。',
    key_hint: '北京地域 DashScope / 百炼 API Key',
  },
  {
    id: 'qwen3-tts-flash-aiden-cn',
    label: 'Qwen3 TTS 美语男声',
    provider: 'qwen',
    base_url: QWEN_DASHSCOPE_CN_TTS_BASE_URL,
    model: QWEN_TTS_DEFAULT_MODEL,
    voice: 'Aiden',
    note: '阿里云百炼北京地域 Qwen3-TTS；Aiden 是官方美语男声音色。',
    key_hint: '北京地域 DashScope / 百炼 API Key',
  },
  {
    id: 'qwen3-tts-instruct-cn',
    label: 'Qwen3 TTS Instruct',
    provider: 'qwen',
    base_url: QWEN_DASHSCOPE_CN_TTS_BASE_URL,
    model: 'qwen3-tts-instruct-flash',
    voice: 'Cherry',
    note: '支持指令控制的千问 3 TTS；当前使用自然清晰朗读默认指令。',
    key_hint: '北京地域 DashScope / 百炼 API Key',
  },
  {
    id: 'qwen3-tts-flash-intl',
    label: 'Qwen3 TTS Intl',
    provider: 'qwen',
    base_url: QWEN_DASHSCOPE_INTL_TTS_BASE_URL,
    model: QWEN_TTS_DEFAULT_MODEL,
    voice: QWEN_TTS_DEFAULT_VOICE,
    note: '新加坡/国际地域 Qwen3-TTS；需要使用对应地域的 DashScope Key。',
    key_hint: '国际地域 DashScope API Key',
  },
  {
    id: 'qwen-tts-latest-cn',
    label: 'Qwen TTS Legacy',
    provider: 'qwen',
    base_url: QWEN_DASHSCOPE_CN_TTS_BASE_URL,
    model: 'qwen-tts-latest',
    voice: 'Cherry',
    note: '旧版 Qwen-TTS，按 Token 计费；新项目优先使用 Qwen3 TTS。',
    key_hint: '北京地域 DashScope / 百炼 API Key',
  },
  {
    id: 'grok',
    label: 'Grok / xAI TTS',
    provider: 'grok',
    base_url: 'https://api.x.ai/v1',
    model: '',
    voice: 'eve',
    note: '单独填写 xAI API Key；Grok TTS 使用 voice_id，例如 eve、ara、leo、rex、sal。',
    key_hint: 'xAI API Key',
  },
  {
    id: 'gemini-tts',
    label: 'Gemini TTS',
    provider: 'gemini',
    base_url: '',
    model: 'gemini-2.5-flash-preview-tts',
    voice: 'Kore',
    note: '单独填写 Gemini API Key；模型和声音按 Google AI Studio 后台调整。',
    key_hint: 'Gemini API Key',
  },
  {
    id: 'openai-speech',
    label: 'OpenAI-compatible Speech',
    provider: 'openai-compatible',
    base_url: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini-tts',
    voice: 'alloy',
    note: '适配 /audio/speech 兼容接口；也可填 Groq 等服务商的 speech Base URL。',
    key_hint: 'Speech API Key',
  },
]

export const featuredTtsPresetIds = new Set(['disabled', 'qwen3-tts-flash-cn', 'mimo-token-plan-sgp-tts', 'gemini-tts'])

export const featuredTtsPresets = ttsPresets.filter((preset) => featuredTtsPresetIds.has(preset.id))
export const advancedTtsPresets = ttsPresets.filter((preset) => !featuredTtsPresetIds.has(preset.id))
