from __future__ import annotations

SCHEMA_VERSION = 2

ENV_PYTHON_MISSING = "ENV_PYTHON_MISSING"
ENV_FFMPEG_MISSING = "ENV_FFMPEG_MISSING"
YOUTUBE_RATE_LIMIT = "YOUTUBE_RATE_LIMIT"
YOUTUBE_N_CHALLENGE = "YOUTUBE_N_CHALLENGE"
YOUTUBE_SUBTITLE_UNAVAILABLE = "YOUTUBE_SUBTITLE_UNAVAILABLE"
MODEL_AUTH_FAILED = "MODEL_AUTH_FAILED"
MODEL_CONNECTION_FAILED = "MODEL_CONNECTION_FAILED"
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
MODEL_QUOTA_EXCEEDED = "MODEL_QUOTA_EXCEEDED"
MODEL_TIMEOUT = "MODEL_TIMEOUT"
MODEL_JSON_INVALID = "MODEL_JSON_INVALID"
TTS_AUTH_FAILED = "TTS_AUTH_FAILED"
TTS_CONNECTION_FAILED = "TTS_CONNECTION_FAILED"
TTS_NOT_FOUND = "TTS_NOT_FOUND"
TTS_QUOTA_EXCEEDED = "TTS_QUOTA_EXCEEDED"
TTS_TIMEOUT = "TTS_TIMEOUT"
EXPORT_QUALITY_GATE_FAILED = "EXPORT_QUALITY_GATE_FAILED"
MEDIA_SUBTITLE_ALIGNMENT_MISMATCH = "MEDIA_SUBTITLE_ALIGNMENT_MISMATCH"
FFMPEG_SLICE_FAILED = "FFMPEG_SLICE_FAILED"
ANKI_EXPORT_FAILED = "ANKI_EXPORT_FAILED"
ANKI_VERIFY_FAILED = "ANKI_VERIFY_FAILED"
WORKER_CANCELLED = "WORKER_CANCELLED"
WORKER_TIMEOUT = "WORKER_TIMEOUT"
UNKNOWN_WORKER_ERROR = "UNKNOWN_WORKER_ERROR"

WORKER_ERROR_CODES = {
    ENV_PYTHON_MISSING,
    ENV_FFMPEG_MISSING,
    YOUTUBE_RATE_LIMIT,
    YOUTUBE_N_CHALLENGE,
    YOUTUBE_SUBTITLE_UNAVAILABLE,
    MODEL_AUTH_FAILED,
    MODEL_CONNECTION_FAILED,
    MODEL_NOT_FOUND,
    MODEL_QUOTA_EXCEEDED,
    MODEL_TIMEOUT,
    MODEL_JSON_INVALID,
    TTS_AUTH_FAILED,
    TTS_CONNECTION_FAILED,
    TTS_NOT_FOUND,
    TTS_QUOTA_EXCEEDED,
    TTS_TIMEOUT,
    EXPORT_QUALITY_GATE_FAILED,
    MEDIA_SUBTITLE_ALIGNMENT_MISMATCH,
    FFMPEG_SLICE_FAILED,
    ANKI_EXPORT_FAILED,
    ANKI_VERIFY_FAILED,
    WORKER_CANCELLED,
    WORKER_TIMEOUT,
    UNKNOWN_WORKER_ERROR,
}
