from __future__ import annotations

CEFR_LABELS = {
    "A1": "A1 入门",
    "A2": "A2 基础",
    "B1": "B1 日常交流",
    "B2": "B2 独立表达",
    "C1": "C1 高阶表达",
    "C2": "C2 接近母语",
}
CEFR_ORDER = list(CEFR_LABELS.keys())

PHRASES_BY_LEVEL = {
    "A1": [
        "want to",
        "have to",
        "going to",
        "right now",
        "a lot of",
        "thank you",
        "i don't know",
    ],
    "A2": [
        "look for",
        "talk about",
        "come on",
        "find out",
        "be good at",
        "get back",
        "sit down",
    ],
    "B1": [
        "in the mood",
        "figure out",
        "make sure",
        "end up",
        "deal with",
        "hang out",
        "pick up",
        "turn out",
    ],
    "B2": [
        "make sense",
        "come up with",
        "get away with",
        "run into",
        "take it personally",
        "let someone down",
        "work something out",
    ],
    "C1": [
        "for what it's worth",
        "out of nowhere",
        "cut someone some slack",
        "read between the lines",
        "the thing is",
        "go out of your way",
    ],
    "C2": [
        "rub someone the wrong way",
        "not miss a beat",
        "get under someone's skin",
        "make a point of",
        "have a way of",
    ],
}

EXPRESSION_PATTERNS = [
    r"\b(?:do not|don't|doesn't|didn't|have no|has no|had no) idea\b",
    r"\b(?:have|has|had) no idea\b",
    r"\bfigure\s+(?:this|that|it|things|something|everything)?\s*out\b",
    r"\bfigure\s+out\b",
    r"\bwork\s+(?:this|that|it|things|something)?\s*out\b",
    r"\bmake\s+sense\b",
    r"\bwhat\s+do\s+you\s+think\s+about\b",
    r"\bhow\s+do\s+you\s+feel\s+about\b",
    r"\bi\s+see\s+what\s+you\s+mean\b",
    r"\bthat\s+reminds\s+me\b",
    r"\bby\s+the\s+way\b",
    r"\bbefore\s+i\s+forget\b",
    r"\bwhile\s+i\s+remember\b",
    r"\bspeaking\s+of\b",
    r"\blook\s+back\b",
    r"\bgo\s+first\b",
    r"\b(?:fall|fell|fallen|falling)\s+asleep\b",
    r"\b(?:wake|woke|wakes|waking)\s+up\b",
    r"\byour\s+turn\b",
    r"\b(?:come|came|comes|coming)\s+out\b",
    r"\bat\s+least\b",
    r"\b(?:stand|stands|standing|stood)\s+up\b",
    r"\bin\s+front\s+of\b",
    r"\bmove\s+on\b",
    r"\bin\s+the\s+mood(?:\s+for|\s+to)?\b",
    r"\bnot\s+(?:really\s+)?in\s+the\s+mood\b",
    r"\bwhat\s+(?:are|were)\s+you\s+talking\s+about\b",
    r"\bknow\s+what\s+you(?:'re| are)\s+talking\s+about\b",
    r"\btell\s+(?:me|you|him|her|us|them|someone|somebody)\s+about\b",
    r"\blet\s+me\s+tell\s+you\s+about\b",
    r"\bfast\s+forward\s+to\b",
    r"\bat\s+a\s+fraction\s+of\b",
    r"\bwhat\s+happens\s+next\b",
    r"\bcaught\s+up\b",
    r"\bactually\s+working\b",
    r"\breally\s+work(?:ing)?\b",
    r"\bas\s+intended\b",
    r"\bworking\s+with\b",
    r"\bopen[-\s]+source\b",
    r"\bopen\s+weights\b",
    r"\bsuch\s+a\s+big\s+deal\b",
    r"\btalk(?:ing)?\s+about\b",
    r"\bcome\s+up\s+with\b",
    r"\bget\s+away\s+with\b",
    r"\brun\s+into\b",
    r"\btake\s+it\s+personally\b",
    r"\blet\s+(?:me|you|him|her|us|them|someone)\s+down\b",
    r"\bdeal\s+with\b",
    r"\bmake\s+sure\b",
    r"\bend\s+up\b",
    r"\bturn\s+out\b",
    r"\bpick\s+up\b",
    r"\bhang\s+out\b",
    r"\bfind\s+out\b",
    r"\blook\s+for\b",
    r"\bget\s+back\b",
    r"\bcome\s+on\b",
    r"\bchanged?\s+my\s+life\b",
    r"\bopening\s+doors\s+to\b",
    r"\bi\s+get\s+it\b",
    r"\bbreak\s+it\s+all\s+down\b",
    r"\bgoing\s+through\s+all\s+the\s+trouble\b",
    r"\bfrom\s+the\s+start\b",
    r"\bin\s+the\s+long\s+run\b",
    r"\bmake\s+a\s+living\b",
    r"\bmore\s+than\s+just\b",
    r"\bconnect\s+with\b",
    r"\bbring\s+to\s+the\s+table\b",
    r"\bfull\s+of\b",
    r"\blife\s+hack\b",
    r"\bchanged?\s+your\s+perspective\b",
    r"\bone\s+or\s+two\s+steps\s+ahead\b",
    r"\balong\s+the\s+way\b",
    r"\bas\s+small\s+as\s+possible\b",
    r"\bas\s+light\s+as\s+possible\b",
    r"\bget\s+the\s+job\s+done\b",
    r"\bget\s+used\s+to\b",
    r"\bgo\s+beyond\b",
    r"\bpacks?\s+a\s+punch\b",
    r"\bset\s+the\s+mood\b",
    r"\bthe\s+right\s+vibe\b",
    r"\bthe\s+whole\s+time\b",
    r"\bin\s+a\s+matter\s+of\s+minutes\b",
    r"\byou\s+never\s+know\b",
    r"\bfeel\s+free\s+to\b",
    r"\bkeep\s+you\s+accountable\b",
    r"\bdrop\s+a\s+comment\b",
]

DISCOVERY_EXPRESSION_PATTERNS = [
    r"\bsuch\s+(?:a|an)\s+[a-z']+\b",
    r"\b(?:kind|sort)\s+of\b",
    r"\b(?:this|that|the)\s+kind\s+of\b",
    r"\ba\s+(?:little\s+)?bit\s+of\b",
    r"\ba\s+little\s+bit\b",
    r"\ba\s+couple\s+of\b",
    r"\b(?:feel|feels|felt|feeling)\s+like\b",
    r"\b(?:look|looks|looked|looking)\s+like\b",
    r"\b(?:sound|sounds|sounded|sounding)\s+like\b",
    r"\b(?:go|goes|went|gone|going)\s+through\b",
    r"\b(?:get|gets|got|getting)\s+through\b",
    r"\b(?:come|comes|came|coming)\s+across\b",
    r"\b(?:show|shows|showed|showing)\s+up\b",
    r"\b(?:set|sets|setting)\s+up\b",
    r"\b(?:start|starts|started|starting)\s+out\b",
    r"\b(?:keep|keeps|kept|keeping)\s+(?:going|doing|trying|moving)\b",
    r"\b(?:bring|brings|brought|bringing)\s+up\b",
    r"\b(?:put|puts|putting)\s+together\b",
    r"\b(?:turn|turns|turned|turning)\s+into\b",
    r"\b(?:make|makes|made|making)\s+it\s+(?:easy|easier|hard|harder|clear|possible)\b",
    r"\b(?:make|makes|made|making)\s+the\s+most\s+of\b",
    r"\bat\s+the\s+same\s+time\b",
    r"\bat\s+(?:some|this|that)\s+point\b",
    r"\bin\s+the\s+first\s+place\b",
    r"\bin\s+the\s+middle\s+of\b",
    r"\bat\s+the\s+end\s+of\b",
    r"\bfor\s+the\s+first\s+time\b",
    r"\bfrom\s+now\s+on\b",
    r"\bright\s+away\b",
    r"\bright\s+after\b",
    r"\bover\s+time\b",
    r"\bmore\s+than\s+just\b",
    r"\bless\s+than\b",
    r"\bas\s+[a-z']+\s+as\s+possible\b",
]

DISCOVERY_PHRASE_PARTICLES = {
    "about",
    "across",
    "along",
    "around",
    "away",
    "back",
    "down",
    "in",
    "into",
    "off",
    "on",
    "out",
    "over",
    "through",
    "together",
    "up",
}

DISCOVERY_PHRASE_VERBS = {
    "bring",
    "brings",
    "brought",
    "come",
    "comes",
    "came",
    "deal",
    "deals",
    "dealt",
    "feel",
    "feels",
    "felt",
    "figure",
    "figures",
    "figured",
    "find",
    "finds",
    "found",
    "get",
    "gets",
    "got",
    "give",
    "gives",
    "gave",
    "go",
    "goes",
    "went",
    "keep",
    "keeps",
    "kept",
    "let",
    "lets",
    "look",
    "looks",
    "looked",
    "make",
    "makes",
    "made",
    "pick",
    "picks",
    "picked",
    "put",
    "puts",
    "run",
    "runs",
    "ran",
    "set",
    "sets",
    "show",
    "shows",
    "showed",
    "start",
    "starts",
    "started",
    "take",
    "takes",
    "took",
    "turn",
    "turns",
    "turned",
    "work",
    "works",
    "worked",
}

DISCOVERY_PREPOSITION_STARTS = {
    "at",
    "by",
    "for",
    "from",
    "in",
    "on",
    "over",
    "under",
    "with",
    "without",
}

DISCOVERY_SIGNAL_WORDS = {
    "bit",
    "couple",
    "end",
    "first",
    "kind",
    "long",
    "middle",
    "more",
    "point",
    "possible",
    "same",
    "sort",
    "time",
    "way",
}

COMMON_FUNCTION_STARTS = {
    "i",
    "you",
    "he",
    "she",
    "we",
    "they",
    "it",
    "can",
    "could",
    "would",
    "should",
    "will",
    "do",
    "does",
    "did",
    "am",
    "are",
    "is",
    "was",
    "were",
    "the",
    "a",
    "an",
    "and",
    "but",
    "so",
}

WEAK_PHRASE_STARTS = {
    "this",
    "that",
    "these",
    "those",
    "there",
    "here",
    "on",
    "as",
    "if",
    "when",
    "where",
    "which",
    "who",
    "more",
    "less",
    "also",
    "first",
}

FILLER_TEXTS = {
    "yeah",
    "yes",
    "no",
    "okay",
    "ok",
    "right",
    "uh",
    "um",
    "hmm",
    "mm",
    "oh",
    "wow",
    "well",
    "sure",
}

NON_TRANSFERABLE_PHRASES = {
    "as you can see",
    "first let me tell you",
    "let me tell you about",
    "let's talk about",
    "today we are going to",
    "today we're going to",
    "first let me tell you about",
}

LOW_VALUE_STANDALONE_PHRASES = {
    "working with",
    "talking about",
    "be able to",
    "figure in",
    "going to",
    "want to",
    "go home",
}
TOO_BASIC_FOR_INTERMEDIATE_PHRASES = {
    "a lot of",
    "be good at",
    "come on",
    "get back",
    "going to",
    "have to",
    "look for",
    "right now",
    "sit down",
    "talk about",
    "talking about",
    "go home",
    "want to",
}
TRANSFERABLE_FUNCTION_FRAME_PHRASES = {
    "it turns out",
    "it turned out",
    "it turns out that",
    "i see what you mean",
    "you know what i mean",
    "it feels like",
    "it looks like",
    "it sounds like",
    "i get it",
    "you never know",
    "if you want to",
}
CARD_TYPE_LABELS = {
    "listening": "听力卡",
    "phrase": "沉浸主卡",
    "cloze": "输出填空卡",
    "knowledge": "知识卡",
}
PHRASE_GUIDE_ALIASES = {
    "fell asleep": "fall asleep",
    "fallen asleep": "fall asleep",
    "woke up": "wake up",
    "woken up": "wake up",
    "came out": "come out",
    "stood up": "stand up",
}

TEMPLATE_NOISE_PATTERNS = [
    r"本地草稿",
    r"值得优先熟悉的表达块",
    r"中文里更接近自然顺口的一句话",
    r"真实口语中，这类表达通常用来快速说明",
    r"这句短.?口语感强",
    r"适合做听力和词伙记忆",
    r"natural object",
    r"use it in short spoken replies",
    r"i hear this pattern in lines like",
]

PHRASE_GUIDES = {
    "what happens next": {
        "chinese": "接下来会发生什么；后续走势。",
        "definition": "表示“接下来会发生什么 / 后续怎么发展”，常用于把注意力引向下一步。",
        "collocations": "wait to see what happens next / see what happens next / what happens next depends on...",
        "context": "常用于讨论计划、比赛、政策、剧情或局势的下一步。",
        "example": "Let's wait and see what happens next.",
        "chinese_feel": "中文里接近“接下来会怎样 / 后面怎么发展”。",
        "why": "它能把注意力从现在转到下一步，非常适合讨论局势变化。",
    },
    "actually working": {
        "chinese": "真的有效；确实在起作用。",
        "definition": "用来判断某个办法、工具或政策是不是真的产生了效果，而不是只看起来不错。",
        "collocations": "Is it actually working? / the plan is actually working / not actually working",
        "context": "常用于评价方法、工具、政策、计划有没有真实效果。",
        "example": "The new routine is simple, but it is actually working.",
        "chinese_feel": "中文里接近“不是看起来厉害，而是真的有效”。",
        "why": "它把重点放在真实效果上，讨论方案和结果时很常用。",
    },
    "caught up": {
        "chinese": "追上了；赶上了。",
        "definition": "表示原本落后的人或事物追到了同一水平。",
        "collocations": "catch up with someone / finally caught up / almost caught up",
        "context": "常用于学习、竞争、技术、进度等场景。",
        "example": "I missed two classes, but I caught up over the weekend.",
        "chinese_feel": "中文里接近“落后之后追上来”。",
        "why": "它比简单说 reach 更口语，适合描述进度和竞争。",
    },
    "make sure": {
        "chinese": "确保；确认一下。",
        "definition": "用来提醒或确认某件事，避免出错或遗漏。",
        "collocations": "make sure you... / make sure everything is ready / just make sure",
        "context": "常用于提醒、安排、确认细节。",
        "example": "Make sure you save the file before you close it.",
        "chinese_feel": "中文里接近“别忘了确认 / 保证”。",
        "why": "它是日常安排里最高频的确认表达之一。",
    },
    "figure out": {
        "chinese": "弄明白；想出办法。",
        "definition": "表示经过思考后弄懂原因、找到办法或解决问题。",
        "collocations": "figure it out / figure out why / figure out what happened",
        "context": "常用于问题解决、理解原因、处理麻烦。",
        "example": "Give me a minute. I'll figure it out.",
        "chinese_feel": "中文里接近“想明白 / 搞定”。",
        "why": "它比 understand 或 solve 更口语、更自然。",
    },
    "look back": {
        "chinese": "回头看；回想起来。",
        "definition": "用来从现在回看过去的经历、决定或感受。",
        "collocations": "look back on it / when I look back / never look back",
        "context": "常用于回忆过去、总结经历或表达事后感受。",
        "example": "When I look back, that mistake was useful.",
        "chinese_feel": "中文里接近“现在回头看”。",
        "why": "它是讲经历和反思时很自然的口语表达。",
    },
    "fall asleep": {
        "chinese": "睡着；入睡。",
        "definition": "表示从醒着进入睡眠状态，强调“睡着了”这个动作。",
        "collocations": "fall asleep on the bus / fall asleep quickly / almost fall asleep",
        "context": "常用于描述疲惫、路上睡着或不小心睡过去。",
        "example": "I fell asleep during the movie.",
        "chinese_feel": "中文里就是“不知不觉睡着了”。",
        "why": "它比 sleep 更准确，能表达“睡着”这个变化。",
    },
    "wake up": {
        "chinese": "醒来；叫醒。",
        "definition": "表示从睡眠状态醒来，也可以表示把某人叫醒。",
        "collocations": "wake up early / wake someone up / suddenly woke up",
        "context": "常用于起床、突然醒来或提醒别人清醒过来。",
        "example": "I woke up before my alarm.",
        "chinese_feel": "中文里接近“醒过来 / 被叫醒”。",
        "why": "这是讲日常作息和突发反应时的核心短语。",
    },
    "go first": {
        "chinese": "先来；先说；先做。",
        "definition": "用来让某人先开始说话、行动或尝试。",
        "collocations": "you go first / let me go first / who wants to go first?",
        "context": "常用于轮流发言、游戏、课堂、讲故事或做决定。",
        "example": "You go first, and I'll answer after you.",
        "chinese_feel": "中文里接近“你先来 / 你先说”。",
        "why": "它是对话交接时很自然的短表达。",
    },
    "your turn": {
        "chinese": "轮到你了。",
        "definition": "用来把行动、发言或选择交给对方。",
        "collocations": "it's your turn / your turn to speak / wait for your turn",
        "context": "常用于聊天、游戏、课堂或轮流做事。",
        "example": "I told my story. Now it's your turn.",
        "chinese_feel": "中文里就是“该你了 / 轮到你了”。",
        "why": "它能让对话自然交接，很适合口语互动。",
    },
    "at least": {
        "chinese": "至少；好歹。",
        "definition": "用来补充一个较低但仍然正面的条件或安慰点。",
        "collocations": "at least we tried / at least they helped / at least for now",
        "context": "常用于安慰、让步、估计数量或降低期待。",
        "example": "It was late, but at least we arrived safely.",
        "chinese_feel": "中文里接近“至少还算... / 好歹...”。",
        "why": "它是表达让步和安慰时非常高频的连接表达。",
    },
    "come out": {
        "chinese": "出来；出现；传出来。",
        "definition": "表示人或东西从某处出来，也可以表示结果、消息或作品出现。",
        "collocations": "come out from behind / come out soon / the truth came out",
        "context": "常用于描述人从某处出现，或消息、结果被公开。",
        "example": "A cat came out from under the table.",
        "chinese_feel": "中文里接近“从里面出来 / 结果出来”。",
        "why": "它能描述空间动作，也能迁移到消息和结果。",
    },
    "stand up": {
        "chinese": "站起来；起身。",
        "definition": "表示从坐着、躺着或倒下的状态站起来。",
        "collocations": "stand up slowly / help someone stand up / stand up in class",
        "context": "常用于身体动作、课堂指令或帮助别人起身。",
        "example": "She helped him stand up after he fell.",
        "chinese_feel": "中文里就是“站起来 / 起身”。",
        "why": "它是描述动作和帮助场景的基础但高频短语。",
    },
    "in front of": {
        "chinese": "在……面前；在……前面。",
        "definition": "用来说明位置，也常表示某事发生在别人面前。",
        "collocations": "in front of everyone / in front of the class / stand in front of",
        "context": "常用于描述公开场合、位置关系或尴尬场景。",
        "example": "I had to speak in front of the team.",
        "chinese_feel": "中文里既可以是“在前面”，也可以是“当着别人面”。",
        "why": "它能把空间位置和社交场景说得很自然。",
    },
}

VIDEO_INTRO_PATTERNS = [
    r"^(so\s+)?(first(ly)?[, ]+)?let me tell you about\b",
    r"^(so\s+)?let'?s talk about\b",
    r"^in this video\b",
    r"^today (we are|we're|i am|i'm) going to\b",
    r"^i want to talk about\b",
    r"^i'?m going to talk about\b",
    r"^as you can see\b",
]

CONTENT_PATTERNS = {
    "profanity": [
        "fuck",
        "fucking",
        "shit",
        "bullshit",
        "damn",
        "asshole",
        "bitch",
    ],
    "romance": [
        "kiss",
        "date",
        "dating",
        "girlfriend",
        "boyfriend",
        "crush",
        "sleep with",
        "hook up",
    ],
    "slang": [
        "gonna",
        "wanna",
        "gotta",
        "kinda",
        "sorta",
        "dude",
        "buddy",
        "bro",
    ],
    "sarcasm": [
        "yeah right",
        "as if",
        "whatever",
        "big deal",
        "seriously",
        "you think",
    ],
    "culture": [
        "thanksgiving",
        "prom",
        "college",
        "super bowl",
        "new york",
        "hollywood",
    ],
    "business": [
        "meeting",
        "deadline",
        "client",
        "boss",
        "promotion",
        "contract",
        "interview",
    ],
}
