from __future__ import annotations

CEFR_LABELS = {
    "A1": "A1 入门",
    "A2": "A2 基础",
    "B1": "B1 日常交流",
    "B2": "B2 独立表达",
    "C1": "C1 高阶表达",
    "C2": "C2 接近母语",
}
CEFR_ORDER = list(CEFR_LABELS.keys())

PHRASES_BY_LEVEL = {
    "A1": [
        "want to",
        "have to",
        "going to",
        "right now",
        "a lot of",
        "thank you",
        "i don't know",
    ],
    "A2": [
        "look for",
        "talk about",
        "come on",
        "find out",
        "be good at",
        "get back",
        "sit down",
    ],
    "B1": [
        "in the mood",
        "figure out",
        "make sure",
        "end up",
        "deal with",
        "hang out",
        "pick up",
        "turn out",
    ],
    "B2": [
        "make sense",
        "come up with",
        "get away with",
        "run into",
        "take it personally",
        "let someone down",
        "work something out",
    ],
    "C1": [
        "for what it's worth",
        "out of nowhere",
        "cut someone some slack",
        "read between the lines",
        "the thing is",
        "go out of your way",
    ],
    "C2": [
        "rub someone the wrong way",
        "not miss a beat",
        "get under someone's skin",
        "make a point of",
        "have a way of",
    ],
}

EXPRESSION_PATTERNS = [
    r"\b(?:do not|don't|doesn't|didn't|have no|has no|had no) idea\b",
    r"\b(?:have|has|had) no idea\b",
    r"\bfigure\s+(?:this|that|it|things|something|everything)?\s*out\b",
    r"\bfigure\s+out\b",
    r"\bwork\s+(?:this|that|it|things|something)?\s*out\b",
    r"\bmake\s+sense\b",
    r"\bwhat\s+do\s+you\s+think\s+about\b",
    r"\bhow\s+do\s+you\s+feel\s+about\b",
    r"\bi\s+see\s+what\s+you\s+mean\b",
    r"\bthat\s+reminds\s+me\b",
    r"\bby\s+the\s+way\b",
    r"\bbefore\s+i\s+forget\b",
    r"\bwhile\s+i\s+remember\b",
    r"\bspeaking\s+of\b",
    r"\blook\s+back\b",
    r"\bgo\s+first\b",
    r"\b(?:fall|fell|fallen|falling)\s+asleep\b",
    r"\b(?:wake|woke|wakes|waking)\s+up\b",
    r"\byour\s+turn\b",
    r"\b(?:come|came|comes|coming)\s+out\b",
    r"\bat\s+least\b",
    r"\b(?:stand|stands|standing|stood)\s+up\b",
    r"\bin\s+front\s+of\b",
    r"\bmove\s+on\b",
    r"\bin\s+the\s+mood(?:\s+for|\s+to)?\b",
    r"\bnot\s+(?:really\s+)?in\s+the\s+mood\b",
    r"\bwhat\s+(?:are|were)\s+you\s+talking\s+about\b",
    r"\bknow\s+what\s+you(?:'re| are)\s+talking\s+about\b",
    r"\btell\s+(?:me|you|him|her|us|them|someone|somebody)\s+about\b",
    r"\blet\s+me\s+tell\s+you\s+about\b",
    r"\bwhat\s+the\s+hell\b",
    r"\bcheck\s+this\s+out\b",
    r"\bwhat'?s\s+up\b",
    r"\ball\s+of\s+a\s+sudden\b",
    r"\b(?:look|looks|looked|looking)\s+into\b",
    r"\blet\s+(?:me|you|him|her|us|them|someone)\s+off\b",
    r"\bturn\s+(?:me|you|him|her|us|them|someone)\s+in\b",
    r"\b(?:cook|cooks|cooked|cooking)\s+up\b",
    r"\b(?:break|breaks|broke|broken|breaking)\s+(?:me|you|him|her|us|them)\s+up\b",
    r"\bfast\s+forward\s+to\b",
    r"\bat\s+a\s+fraction\s+of\b",
    r"\bwhat\s+happens\s+next\b",
    r"\bcaught\s+up\b",
    r"\bactually\s+working\b",
    r"\breally\s+work(?:ing)?\b",
    r"\bas\s+intended\b",
    r"\bworking\s+with\b",
    r"\bopen[-\s]+source\b",
    r"\bopen\s+weights\b",
    r"\bsuch\s+a\s+big\s+deal\b",
    r"\btalk(?:ing)?\s+about\b",
    r"\bcome\s+up\s+with\b",
    r"\bget\s+away\s+with\b",
    r"\brun\s+into\b",
    r"\btake\s+it\s+personally\b",
    r"\blet\s+(?:me|you|him|her|us|them|someone)\s+down\b",
    r"\bdeal\s+with\b",
    r"\bmake\s+sure\b",
    r"\bend\s+up\b",
    r"\bturn\s+out\b",
    r"\bpick\s+up\b",
    r"\bhang\s+out\b",
    r"\bfind\s+out\b",
    r"\blook\s+for\b",
    r"\bget\s+back\b",
    r"\bcome\s+on\b",
    r"\bchanged?\s+my\s+life\b",
    r"\bopening\s+doors\s+to\b",
    r"\bi\s+get\s+it\b",
    r"\bbreak\s+it\s+all\s+down\b",
    r"\bgoing\s+through\s+all\s+the\s+trouble\b",
    r"\bfrom\s+the\s+start\b",
    r"\bin\s+the\s+long\s+run\b",
    r"\bmake\s+a\s+living\b",
    r"\bmore\s+than\s+just\b",
    r"\bconnect\s+with\b",
    r"\bbring\s+to\s+the\s+table\b",
    r"\bfull\s+of\b",
    r"\blife\s+hack\b",
    r"\bchanged?\s+your\s+perspective\b",
    r"\bone\s+or\s+two\s+steps\s+ahead\b",
    r"\balong\s+the\s+way\b",
    r"\bas\s+small\s+as\s+possible\b",
    r"\bas\s+light\s+as\s+possible\b",
    r"\bget\s+the\s+job\s+done\b",
    r"\bget\s+used\s+to\b",
    r"\bgo\s+beyond\b",
    r"\bpacks?\s+a\s+punch\b",
    r"\bset\s+the\s+mood\b",
    r"\bthe\s+right\s+vibe\b",
    r"\bthe\s+whole\s+time\b",
    r"\bin\s+a\s+matter\s+of\s+minutes\b",
    r"\byou\s+never\s+know\b",
    r"\bfeel\s+free\s+to\b",
    r"\bkeep\s+you\s+accountable\b",
    r"\bdrop\s+a\s+comment\b",
]

DISCOVERY_EXPRESSION_PATTERNS = [
    r"\bsuch\s+(?:a|an)\s+[a-z']+\b",
    r"\b(?:kind|sort)\s+of\b",
    r"\b(?:this|that|the)\s+kind\s+of\b",
    r"\ba\s+(?:little\s+)?bit\s+of\b",
    r"\ba\s+little\s+bit\b",
    r"\ba\s+couple\s+of\b",
    r"\b(?:feel|feels|felt|feeling)\s+like\b",
    r"\b(?:look|looks|looked|looking)\s+like\b",
    r"\b(?:sound|sounds|sounded|sounding)\s+like\b",
    r"\b(?:go|goes|went|gone|going)\s+through\b",
    r"\b(?:get|gets|got|getting)\s+through\b",
    r"\b(?:come|comes|came|coming)\s+across\b",
    r"\b(?:show|shows|showed|showing)\s+up\b",
    r"\b(?:set|sets|setting)\s+up\b",
    r"\b(?:start|starts|started|starting)\s+out\b",
    r"\b(?:keep|keeps|kept|keeping)\s+(?:going|doing|trying|moving)\b",
    r"\b(?:bring|brings|brought|bringing)\s+up\b",
    r"\b(?:put|puts|putting)\s+together\b",
    r"\b(?:turn|turns|turned|turning)\s+into\b",
    r"\b(?:make|makes|made|making)\s+it\s+(?:easy|easier|hard|harder|clear|possible)\b",
    r"\b(?:make|makes|made|making)\s+the\s+most\s+of\b",
    r"\bat\s+the\s+same\s+time\b",
    r"\bat\s+(?:some|this|that)\s+point\b",
    r"\bin\s+the\s+first\s+place\b",
    r"\bin\s+the\s+middle\s+of\b",
    r"\bat\s+the\s+end\s+of\b",
    r"\bfor\s+the\s+first\s+time\b",
    r"\bfrom\s+now\s+on\b",
    r"\bright\s+away\b",
    r"\bright\s+after\b",
    r"\bover\s+time\b",
    r"\bmore\s+than\s+just\b",
    r"\bless\s+than\b",
    r"\bas\s+[a-z']+\s+as\s+possible\b",
]

DISCOVERY_PHRASE_PARTICLES = {
    "about",
    "across",
    "along",
    "around",
    "away",
    "back",
    "down",
    "in",
    "into",
    "off",
    "on",
    "out",
    "over",
    "through",
    "together",
    "up",
}

DISCOVERY_PHRASE_VERBS = {
    "bring",
    "brings",
    "brought",
    "come",
    "comes",
    "came",
    "deal",
    "deals",
    "dealt",
    "feel",
    "feels",
    "felt",
    "figure",
    "figures",
    "figured",
    "find",
    "finds",
    "found",
    "get",
    "gets",
    "got",
    "give",
    "gives",
    "gave",
    "go",
    "goes",
    "went",
    "keep",
    "keeps",
    "kept",
    "let",
    "lets",
    "look",
    "looks",
    "looked",
    "make",
    "makes",
    "made",
    "pick",
    "picks",
    "picked",
    "put",
    "puts",
    "run",
    "runs",
    "ran",
    "set",
    "sets",
    "show",
    "shows",
    "showed",
    "start",
    "starts",
    "started",
    "take",
    "takes",
    "took",
    "turn",
    "turns",
    "turned",
    "work",
    "works",
    "worked",
}

DISCOVERY_PREPOSITION_STARTS = {
    "at",
    "by",
    "for",
    "from",
    "in",
    "on",
    "over",
    "under",
    "with",
    "without",
}

DISCOVERY_SIGNAL_WORDS = {
    "bit",
    "couple",
    "end",
    "first",
    "kind",
    "long",
    "middle",
    "more",
    "point",
    "possible",
    "same",
    "sort",
    "time",
    "way",
}

COMMON_FUNCTION_STARTS = {
    "i",
    "you",
    "he",
    "she",
    "we",
    "they",
    "it",
    "can",
    "could",
    "would",
    "should",
    "will",
    "do",
    "does",
    "did",
    "am",
    "are",
    "is",
    "was",
    "were",
    "the",
    "a",
    "an",
    "and",
    "but",
    "so",
}

WEAK_PHRASE_STARTS = {
    "this",
    "that",
    "these",
    "those",
    "there",
    "here",
    "on",
    "as",
    "if",
    "when",
    "where",
    "which",
    "who",
    "more",
    "less",
    "also",
    "first",
}

FILLER_TEXTS = {
    "yeah",
    "yes",
    "no",
    "okay",
    "ok",
    "right",
    "uh",
    "um",
    "hmm",
    "mm",
    "oh",
    "wow",
    "well",
    "sure",
}

NON_TRANSFERABLE_PHRASES = {
    "as you can see",
    "first let me tell you",
    "let me tell you about",
    "let's talk about",
    "today we are going to",
    "today we're going to",
    "first let me tell you about",
}

LOW_VALUE_STANDALONE_PHRASES = {
    "working with",
    "talking about",
    "be able to",
    "figure in",
    "going to",
    "want to",
    "go home",
}
TOO_BASIC_FOR_INTERMEDIATE_PHRASES = {
    "a lot of",
    "be good at",
    "come on",
    "get back",
    "going to",
    "have to",
    "look for",
    "right now",
    "sit down",
    "talk about",
    "talking about",
    "go home",
    "want to",
}
TRANSFERABLE_FUNCTION_FRAME_PHRASES = {
    "it turns out",
    "it turned out",
    "it turns out that",
    "i see what you mean",
    "you know what i mean",
    "it feels like",
    "it looks like",
    "it sounds like",
    "i get it",
    "you never know",
    "if you want to",
}
CARD_TYPE_LABELS = {
    "listening": "听力卡",
    "phrase": "表达卡",
    "cloze": "输出填空卡",
    "knowledge": "知识卡",
}
PHRASE_GUIDE_ALIASES = {
    "fell asleep": "fall asleep",
    "fallen asleep": "fall asleep",
    "woke up": "wake up",
    "woken up": "wake up",
    "came out": "come out",
    "stood up": "stand up",
    "looks like": "look like",
    "looked like": "look like",
    "looking like": "look like",
    "picked up": "pick up",
    "looked into": "look into",
    "looking into": "look into",
    "worked out": "work out",
    "working out": "work out",
    "turn me in": "turn someone in",
    "turn you in": "turn someone in",
    "turn him in": "turn someone in",
    "turn her in": "turn someone in",
    "turn us in": "turn someone in",
    "turn them in": "turn someone in",
    "let me off": "let someone off",
    "let you off": "let someone off",
    "let him off": "let someone off",
    "let her off": "let someone off",
    "let us off": "let someone off",
    "let them off": "let someone off",
    "cooked up": "cook up",
    "cooking up": "cook up",
    "broke me up": "break someone up",
    "broke you up": "break someone up",
    "broke him up": "break someone up",
    "broke her up": "break someone up",
}

TEMPLATE_NOISE_PATTERNS = [
    r"本地草稿",
    r"预览草稿",
    r"本地待审",
    r"待精修",
    r"正式导出前",
    r"本句目标表达",
    r"需要用\s*AI\s*精修",
    r"值得优先熟悉的表达块",
    r"中文里更接近自然顺口的一句话",
    r"真实口语中，这类表达通常用来快速说明",
    r"这句短.?口语感强",
    r"适合做听力和词伙记忆",
    r"natural object",
    r"use .* in a complete sentence",
    r"use it in short spoken replies",
    r"i hear this pattern in lines like",
]

PHRASE_GUIDES = {
    "look like": {
        "chinese": "看起来像；感觉像。",
        "definition": "用来根据外表、迹象或感觉判断某人/某物像什么。",
        "collocations": "look like trouble / looks like rain / look like someone",
        "context": "常用于第一眼判断、猜测状况或形容画面感。",
        "example": "It looks like rain, so take an umbrella.",
        "chinese_feel": "中文里接近“看着像 / 感觉像”。",
        "why": "它能把观察和判断自然连起来，是影视对白里很高频的口语框架。",
        "teacher_note": "look like 后面接名词或完整样子；不要逐词想成“看”。",
    },
    "at some point": {
        "chinese": "在某个时候；迟早有一刻。",
        "definition": "用来指一个不精确但一定会发生或需要处理的时间点。",
        "collocations": "at some point today / at some point we need to... / happen at some point",
        "context": "常用于安排、提醒、压力拖延或迟早要面对的事。",
        "example": "At some point, we need to talk about the budget.",
        "chinese_feel": "中文里接近“总得找个时候 / 迟早”。",
        "why": "它比 sometime 更有“这事终究要发生”的语气。",
        "teacher_note": "用 at some point 软化时间，不必说具体几点。",
    },
    "look into": {
        "chinese": "查一下；调查了解。",
        "definition": "表示去了解、检查或调查一个问题，再给出结果。",
        "collocations": "look into it / look into the issue / let me look into that",
        "context": "常用于工作、客服、朋友帮忙查事情。",
        "example": "I'll look into it and call you back.",
        "chinese_feel": "中文里接近“我去查查 / 了解一下”。",
        "why": "它是处理问题时很自然、很礼貌的回应。",
        "teacher_note": "别人提出问题时，用 let me look into that 比 I will check 更口语。",
    },
    "let someone off": {
        "chinese": "放过某人；从轻处理。",
        "definition": "表示不惩罚某人，或只给较轻的惩罚/要求。",
        "collocations": "let you off with a warning / let him off easy / let someone off the hook",
        "context": "常用于处罚、讲价、老师/警察/老板从轻处理。",
        "example": "The teacher let me off with a warning.",
        "chinese_feel": "中文里接近“这次先放你一马”。",
        "why": "它把“本来要处罚，但这次轻一点”的语气说得很地道。",
        "teacher_note": "let you off 后面常接 with...，说明从轻处理的方式。",
    },
    "turn someone in": {
        "chinese": "举报某人；把某人交给警方/权威。",
        "definition": "表示把做错事的人报告给警方、老师或负责人。",
        "collocations": "turn him in / turn yourself in / turn someone in to the police",
        "context": "常用于犯罪、违规、背叛或自首场景。",
        "example": "His partner finally turned him in.",
        "chinese_feel": "中文里接近“把他供出来 / 举报”。",
        "why": "它是剧情对白里表达举报、自首和背叛的核心短语。",
        "teacher_note": "turn someone in 里的 someone 放在 turn 和 in 中间。",
    },
    "cook up": {
        "chinese": "编造；策划；弄出。",
        "definition": "除了做饭，也常表示临时想出、编出或搞出某个计划/借口。",
        "collocations": "cook up a plan / cook up an excuse / cook up a batch",
        "context": "常用于计划、借口、阴谋，也可用于真的做出一批东西。",
        "example": "They cooked up a story to explain the delay.",
        "chinese_feel": "中文里接近“临时编/鼓捣出”。",
        "why": "它比 make 更有口语感，常带一点不正式甚至可疑的味道。",
        "teacher_note": "看上下文判断是“做出”还是“编造/策划”。",
    },
    "break someone up": {
        "chinese": "让某人很难过；让某人大笑。",
        "definition": "根据上下文可表示让人情绪崩掉、难过，或让人大笑到不行。",
        "collocations": "it broke me up / that joke broke us up / break someone up about something",
        "context": "常用于强烈情绪反应：悲伤、震动或爆笑。",
        "example": "The news really broke her up.",
        "chinese_feel": "中文里接近“把我整难受了 / 笑崩了”。",
        "why": "它能表达普通 sad 或 laugh 说不出的强烈反应。",
        "teacher_note": "结合语气判断是难过还是大笑；影视对白常用它表达情绪冲击。",
    },
    "all of a sudden": {
        "chinese": "突然一下；冷不丁。",
        "definition": "用来强调某件事突然发生，通常带一点意外感。",
        "collocations": "all of a sudden, he left / all of a sudden it changed / all of a sudden at age...",
        "context": "常用于讲故事、转折、意外变化。",
        "example": "All of a sudden, the room went quiet.",
        "chinese_feel": "中文里接近“突然一下子”。",
        "why": "它比 suddenly 更口语、更有讲故事的节奏。",
        "teacher_note": "常放在句首，引出一个突然变化。",
    },
    "check this out": {
        "chinese": "看这个；你瞧瞧。",
        "definition": "用来叫别人注意你要展示的东西或信息。",
        "collocations": "come check this out / check this out, guys / you should check this out",
        "context": "常用于展示视频、东西、发现或有趣信息。",
        "example": "Come check this out. The view is amazing.",
        "chinese_feel": "中文里接近“快来看这个”。",
        "why": "它是把别人注意力拉过来的高频口语句。",
        "teacher_note": "check this out 不是正式的检查，而是“来看/听这个”。",
    },
    "what the hell": {
        "chinese": "到底怎么回事；搞什么。",
        "definition": "用来表达惊讶、生气或不理解，语气比较强。",
        "collocations": "what the hell is this? / what the hell happened? / what the hell are you doing?",
        "context": "常用于冲突、惊讶、质问；语气粗，不适合正式场合。",
        "example": "What the hell are you doing here?",
        "chinese_feel": "中文里接近“这到底什么鬼”。",
        "why": "影视对白里很常见，能帮助理解真实语气和情绪强度。",
        "teacher_note": "这是粗口语气，理解即可；正式场合换成 what is going on。",
    },
    "what's up": {
        "chinese": "怎么了；最近怎样。",
        "definition": "可用来打招呼，也可询问发生了什么事。",
        "collocations": "what's up? / so, what's up? / what's up with that?",
        "context": "常用于朋友间开场、询问状态或发现不对劲时追问。",
        "example": "Hey, what's up? You look worried.",
        "chinese_feel": "中文里接近“咋了 / 最近怎么样”。",
        "why": "它是自然对话开场和追问状况的核心短句。",
        "teacher_note": "根据语气判断是打招呼还是问“出什么事了”。",
    },
    "what happens next": {
        "chinese": "接下来会发生什么；后续走势。",
        "definition": "表示“接下来会发生什么 / 后续怎么发展”，常用于把注意力引向下一步。",
        "collocations": "wait to see what happens next / see what happens next / what happens next depends on...",
        "context": "常用于讨论计划、比赛、政策、剧情或局势的下一步。",
        "example": "Let's wait and see what happens next.",
        "chinese_feel": "中文里接近“接下来会怎样 / 后面怎么发展”。",
        "why": "它能把注意力从现在转到下一步，非常适合讨论局势变化。",
    },
    "actually working": {
        "chinese": "真的有效；确实在起作用。",
        "definition": "用来判断某个办法、工具或政策是不是真的产生了效果，而不是只看起来不错。",
        "collocations": "Is it actually working? / the plan is actually working / not actually working",
        "context": "常用于评价方法、工具、政策、计划有没有真实效果。",
        "example": "The new routine is simple, but it is actually working.",
        "chinese_feel": "中文里接近“不是看起来厉害，而是真的有效”。",
        "why": "它把重点放在真实效果上，讨论方案和结果时很常用。",
    },
    "caught up": {
        "chinese": "追上了；赶上了。",
        "definition": "表示原本落后的人或事物追到了同一水平。",
        "collocations": "catch up with someone / finally caught up / almost caught up",
        "context": "常用于学习、竞争、技术、进度等场景。",
        "example": "I missed two classes, but I caught up over the weekend.",
        "chinese_feel": "中文里接近“落后之后追上来”。",
        "why": "它比简单说 reach 更口语，适合描述进度和竞争。",
    },
    "make sure": {
        "chinese": "确保；确认一下。",
        "definition": "用来提醒或确认某件事，避免出错或遗漏。",
        "collocations": "make sure you... / make sure everything is ready / just make sure",
        "context": "常用于提醒、安排、确认细节。",
        "example": "Make sure you save the file before you close it.",
        "chinese_feel": "中文里接近“别忘了确认 / 保证”。",
        "why": "它是日常安排里最高频的确认表达之一。",
    },
    "hang out": {
        "chinese": "待着；一起消磨时间。",
        "definition": "表示和别人轻松地待在一起，或在某处随便待一会儿。",
        "collocations": "hang out here / hang out with friends / just hang out for a second",
        "context": "常用于朋友、休息、等人或临时停留。",
        "example": "We hung out at the cafe after class.",
        "chinese_feel": "中文里接近“待会儿 / 一起混一会儿”。",
        "why": "它比 stay 或 play 更像真实口语里的轻松陪伴。",
        "teacher_note": "hang out 可以是不做具体事，只是一起待着。",
    },
    "pick up": {
        "chinese": "拿起；接人；顺手买；学会。",
        "definition": "根据上下文表示拿起、接某人、顺手买到，或逐渐学会。",
        "collocations": "pick up the phone / pick someone up / pick up groceries / pick up a habit",
        "context": "常用于日常动作、接送、购物和技能习得。",
        "example": "Can you pick me up after work?",
        "chinese_feel": "中文里要按语境理解成“拿/接/顺手买/学会”。",
        "why": "它一词多义但非常高频，影视对白里经常靠上下文判断。",
        "teacher_note": "看到 pick up 先看后面接的是人、物、地点还是技能。",
    },
    "figure out": {
        "chinese": "弄明白；想出办法。",
        "definition": "表示经过思考后弄懂原因、找到办法或解决问题。",
        "collocations": "figure it out / figure out why / figure out what happened",
        "context": "常用于问题解决、理解原因、处理麻烦。",
        "example": "Give me a minute. I'll figure it out.",
        "chinese_feel": "中文里接近“想明白 / 搞定”。",
        "why": "它比 understand 或 solve 更口语、更自然。",
    },
    "work out": {
        "chinese": "解决；成功；锻炼。",
        "definition": "根据上下文表示事情顺利解决、计划成功，或进行健身锻炼。",
        "collocations": "work it out / it worked out / work out of a place / work out at the gym",
        "context": "常用于结果、安排、关系问题或运动场景。",
        "example": "The plan worked out better than I expected.",
        "chinese_feel": "中文里接近“最后成了 / 解决了”。",
        "why": "它能自然表达“事情最后怎么发展”，比 solve 更口语。",
        "teacher_note": "work out 的意思高度依赖上下文；先判断是在说结果、解决问题还是健身。",
    },
    "make a living": {
        "chinese": "谋生；靠……赚钱生活。",
        "definition": "表示通过某种工作或方式挣钱维持生活。",
        "collocations": "make a living as a teacher / make a living from music / gotta make a living",
        "context": "常用于谈工作、职业、收入压力或生存方式。",
        "example": "She makes a living by repairing old bikes.",
        "chinese_feel": "中文里接近“靠这个吃饭”。",
        "why": "它比 make money 更强调维持生活和职业压力。",
        "teacher_note": "make a living 后面常接 as / from / by，说明靠什么谋生。",
    },
    "look back": {
        "chinese": "回头看；回想起来。",
        "definition": "用来从现在回看过去的经历、决定或感受。",
        "collocations": "look back on it / when I look back / never look back",
        "context": "常用于回忆过去、总结经历或表达事后感受。",
        "example": "When I look back, that mistake was useful.",
        "chinese_feel": "中文里接近“现在回头看”。",
        "why": "它是讲经历和反思时很自然的口语表达。",
    },
    "fall asleep": {
        "chinese": "睡着；入睡。",
        "definition": "表示从醒着进入睡眠状态，强调“睡着了”这个动作。",
        "collocations": "fall asleep on the bus / fall asleep quickly / almost fall asleep",
        "context": "常用于描述疲惫、路上睡着或不小心睡过去。",
        "example": "I fell asleep during the movie.",
        "chinese_feel": "中文里就是“不知不觉睡着了”。",
        "why": "它比 sleep 更准确，能表达“睡着”这个变化。",
    },
    "wake up": {
        "chinese": "醒来；叫醒。",
        "definition": "表示从睡眠状态醒来，也可以表示把某人叫醒。",
        "collocations": "wake up early / wake someone up / suddenly woke up",
        "context": "常用于起床、突然醒来或提醒别人清醒过来。",
        "example": "I woke up before my alarm.",
        "chinese_feel": "中文里接近“醒过来 / 被叫醒”。",
        "why": "这是讲日常作息和突发反应时的核心短语。",
    },
    "go first": {
        "chinese": "先来；先说；先做。",
        "definition": "用来让某人先开始说话、行动或尝试。",
        "collocations": "you go first / let me go first / who wants to go first?",
        "context": "常用于轮流发言、游戏、课堂、讲故事或做决定。",
        "example": "You go first, and I'll answer after you.",
        "chinese_feel": "中文里接近“你先来 / 你先说”。",
        "why": "它是对话交接时很自然的短表达。",
    },
    "your turn": {
        "chinese": "轮到你了。",
        "definition": "用来把行动、发言或选择交给对方。",
        "collocations": "it's your turn / your turn to speak / wait for your turn",
        "context": "常用于聊天、游戏、课堂或轮流做事。",
        "example": "I told my story. Now it's your turn.",
        "chinese_feel": "中文里就是“该你了 / 轮到你了”。",
        "why": "它能让对话自然交接，很适合口语互动。",
    },
    "at least": {
        "chinese": "至少；好歹。",
        "definition": "用来补充一个较低但仍然正面的条件或安慰点。",
        "collocations": "at least we tried / at least they helped / at least for now",
        "context": "常用于安慰、让步、估计数量或降低期待。",
        "example": "It was late, but at least we arrived safely.",
        "chinese_feel": "中文里接近“至少还算... / 好歹...”。",
        "why": "它是表达让步和安慰时非常高频的连接表达。",
    },
    "come out": {
        "chinese": "出来；出现；传出来。",
        "definition": "表示人或东西从某处出来，也可以表示结果、消息或作品出现。",
        "collocations": "come out from behind / come out soon / the truth came out",
        "context": "常用于描述人从某处出现，或消息、结果被公开。",
        "example": "A cat came out from under the table.",
        "chinese_feel": "中文里接近“从里面出来 / 结果出来”。",
        "why": "它能描述空间动作，也能迁移到消息和结果。",
    },
    "stand up": {
        "chinese": "站起来；起身。",
        "definition": "表示从坐着、躺着或倒下的状态站起来。",
        "collocations": "stand up slowly / help someone stand up / stand up in class",
        "context": "常用于身体动作、课堂指令或帮助别人起身。",
        "example": "She helped him stand up after he fell.",
        "chinese_feel": "中文里就是“站起来 / 起身”。",
        "why": "它是描述动作和帮助场景的基础但高频短语。",
    },
    "in front of": {
        "chinese": "在……面前；在……前面。",
        "definition": "用来说明位置，也常表示某事发生在别人面前。",
        "collocations": "in front of everyone / in front of the class / stand in front of",
        "context": "常用于描述公开场合、位置关系或尴尬场景。",
        "example": "I had to speak in front of the team.",
        "chinese_feel": "中文里既可以是“在前面”，也可以是“当着别人面”。",
        "why": "它能把空间位置和社交场景说得很自然。",
    },
}

VIDEO_INTRO_PATTERNS = [
    r"^(so\s+)?(first(ly)?[, ]+)?let me tell you about\b",
    r"^(so\s+)?let'?s talk about\b",
    r"^in this video\b",
    r"^today (we are|we're|i am|i'm) going to\b",
    r"^i want to talk about\b",
    r"^i'?m going to talk about\b",
    r"^as you can see\b",
]

CONTENT_PATTERNS = {
    "profanity": [
        "fuck",
        "fucking",
        "shit",
        "bullshit",
        "damn",
        "asshole",
        "bitch",
    ],
    "romance": [
        "kiss",
        "date",
        "dating",
        "girlfriend",
        "boyfriend",
        "crush",
        "sleep with",
        "hook up",
    ],
    "slang": [
        "gonna",
        "wanna",
        "gotta",
        "kinda",
        "sorta",
        "dude",
        "buddy",
        "bro",
    ],
    "sarcasm": [
        "yeah right",
        "as if",
        "whatever",
        "big deal",
        "seriously",
        "you think",
    ],
    "culture": [
        "thanksgiving",
        "prom",
        "college",
        "super bowl",
        "new york",
        "hollywood",
    ],
    "business": [
        "meeting",
        "deadline",
        "client",
        "boss",
        "promotion",
        "contract",
        "interview",
    ],
}
